#!/usr/bin/env bash
# make-bot-env.sh — create bot/.env for running the bot LOCALLY (your laptop,
# for testing) instead of on a host like Fly.
#
# WHAT IT TOUCHES: writes bot/.env (chmod 600) from hidden prompts. bot/.env is
# gitignored, so it is never committed — but it is a plaintext file on your disk,
# so treat it like a password file. Values are not echoed while you type.
#
#   bash scripts/make-bot-env.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/bot/.env"

if [ -f "$ENV_FILE" ]; then
  read -r -p "bot/.env already exists. Overwrite it? [y/N] " ok
  case "$ok" in y|Y) ;; *) echo "Aborted; left existing file untouched."; exit 0 ;; esac
fi

echo
echo "Filling bot/.env (input hidden; press Enter to leave a value blank)."
echo

hidden() { printf '  %s: ' "$1"; IFS= read -rs V || true; echo; }
plain()  { printf '  %s: ' "$1"; IFS= read -r  V || true; }

hidden "DISCORD_BOT_TOKEN";       BOT_TOKEN="$V"
plain  "DISCORD_GUILD_ID (optional)"; GUILD="$V"
hidden "OPENROUTER_API_KEY (sk-or-...)"; OR_KEY="$V"
hidden "GITHUB_DISPATCH_TOKEN";   GH_TOKEN="$V"
plain  "GITHUB_REPO (owner/repo)"; GH_REPO="$V"
hidden "EXA_API_KEY (recommended for web research; blank = keyless DuckDuckGo)"; EXA_KEY="$V"
# Not used by the bot itself — staged here so set-github-secrets.sh can mirror it
# up as the DISCORD_WEBHOOK_URL Actions secret (lets finished actions post the PR
# link back to a channel). Blank to skip.
plain  "DISCORD_WEBHOOK_URL (optional; for set-github-secrets.sh)"; WEBHOOK="$V"
unset V

umask 077   # so the file is created private (600)
cat > "$ENV_FILE" <<EOF
# Generated by scripts/make-bot-env.sh — local secrets, gitignored. Do not commit.
DISCORD_BOT_TOKEN=$BOT_TOKEN
DISCORD_GUILD_ID=$GUILD
OPENROUTER_API_KEY=$OR_KEY
GITHUB_DISPATCH_TOKEN=$GH_TOKEN
GITHUB_REPO=$GH_REPO
EXA_API_KEY=$EXA_KEY
DISCORD_WEBHOOK_URL=$WEBHOOK
EOF
chmod 600 "$ENV_FILE"
unset BOT_TOKEN GUILD OR_KEY GH_TOKEN GH_REPO EXA_KEY WEBHOOK

echo "✓ Wrote $ENV_FILE (permissions 600)."
echo "Run the bot locally with:"
echo "  cd bot && uv sync && uv run python -m bot"
